### ISSUE TITLE
Cannot read field "enabled" because "config" is null

### ISSUE THREAD

**Issue by maxsspeaker** [Mirsario/Minecraft-CameraOverhaul#36]
when entering the world or server, an error occurs:
```
java.lang.NullPointerException: Cannot read field "enabled" because "config" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19.1+build.6)
	at mirsario.cameraoverhaul.common.systems.CameraSystem.OnCameraUpdate(CameraSystem.java:52)
	at net.minecraft.client.render.Camera.handler$zbj000$OnCameraUpdate(Camera:526)
	at net.minecraft.client.render.Camera.update(Camera:61)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1029)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:816)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1176)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:767)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$zji000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:8519)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:794)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$zji000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:8519)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:794)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$zji000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:8519)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:794)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$zji000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:8519)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:794)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
```
is it possible to fix this somehow?
I use quilt loader

**Comment by Mirsario** [comment]
Your config file at `.minecraft/config/cameraoverhaul.json` is most likely corrupt, try deleting it.

**Comment by maxsspeaker** [comment]
Config file deleted and it is not even created when i try to login to server or local world.
As I said earlier, when I try to enter the world or the server, minecraft crashes
